name:        galois-field
version:     0.2.1
synopsis:    Galois field library
description: An efficient implementation of Galois fields used in cryptography research
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/galois-field
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses

dependencies:
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - integer-gmp
  - MonadRandom
  - tasty-quickcheck
  - wl-pprint-text

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -O2
  - -Wall

library:
  exposed-modules:
    - BinaryField
    - ExtensionField
    - GaloisField
    - PrimeField
  source-dirs:
    - src

tests:
  galois-field-tests:
    main: Main
    dependencies:
      - tasty
    source-dirs:
      - tests
      - src

benchmarks:
  galois-field-benchmarks:
    main: Main
    dependencies:
      - criterion
    source-dirs:
      - benchmarks
      - src
