name:        galois-field
version:     0.2.0
synopsis:    Galois field library
description: Galois field library for cryptography research
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/galois-field
category:    Cryptography

default-extensions:
  - LambdaCase
  - RecordWildCards
  - OverloadedStrings
  - NoImplicitPrelude
  - FlexibleInstances
  - FlexibleContexts
  - ScopedTypeVariables
  - RankNTypes
  - DataKinds
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses

dependencies:
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - integer-gmp
  - MonadRandom
  - tasty-quickcheck
  - wl-pprint-text

extra-source-files:
  - README.md
  - ChangeLog.md

library:
  exposed-modules:
    - GaloisField
    - PrimeField
    - ExtensionField
  ghc-options:
    - -O2
    - -Wall
  other-modules:
    - PolynomialRing
  source-dirs:
    - src

tests:
  galois-field-tests:
    main: Main
    dependencies:
      - tasty
      - tasty-discover
    ghc-options:
      - -O2
    source-dirs:
      - tests
      - src

benchmarks:
  galois-field-benchmarks:
    main: Main
    dependencies:
      - criterion
    ghc-options:
      - -O2
    source-dirs:
      - benchmarks
      - src
