name:        galois-field
version:     0.1.1
synopsis:    Galois field
description: Finite field library
maintainer:  Adjoint Inc (info@adjoint.io)
license:     MIT
github:      adjoint-io/galois-field
category:    Cryptography

extra-source-files:
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - protolude >= 0.2
  - integer-gmp
  - tasty-quickcheck
  - wl-pprint-text

library:
  source-dirs: src
  ghc-options:
    -O2
    -Wall
  default-extensions:
    - LambdaCase
    - RecordWildCards
    - OverloadedStrings
    - NoImplicitPrelude
    - FlexibleInstances
    - FlexibleContexts
    - ScopedTypeVariables
    - RankNTypes
    - DataKinds
    - DeriveGeneric
    - GeneralizedNewtypeDeriving
    - KindSignatures
    - MultiParamTypeClasses
  exposed-modules:
    - GaloisField
    - PrimeField
    - ExtensionField
  other-modules:
    - PolynomialRing

tests:
  tests:
    main: Main.hs
    source-dirs:
      - src
      - tests
    dependencies:
      - base >= 4.7 && < 5
      - protolude >= 0.2
      - tasty
      - tasty-discover
      - tasty-quickcheck
    default-extensions:
      - LambdaCase
      - RecordWildCards
      - OverloadedStrings
      - NoImplicitPrelude
      - FlexibleInstances
      - FlexibleContexts
      - ScopedTypeVariables
      - RankNTypes
      - DataKinds
      - DeriveGeneric
      - GeneralizedNewtypeDeriving
      - KindSignatures
      - MultiParamTypeClasses
    other-modules:
      - GaloisField
      - PrimeField
      - PolynomialRing
      - ExtensionField
      - GaloisFieldTests
      - PrimeFieldTests
      - PolynomialRingTests
      - ExtensionFieldTests

benchmarks:
  benchmarks:
    main: Main.hs
    source-dirs:
      - src
      - benchmarks
    dependencies:
      - base >= 4.7 && < 5
      - protolude >= 0.2
      - criterion
    default-extensions:
      - LambdaCase
      - RecordWildCards
      - OverloadedStrings
      - NoImplicitPrelude
      - FlexibleInstances
      - FlexibleContexts
      - ScopedTypeVariables
      - RankNTypes
      - DataKinds
      - DeriveGeneric
      - GeneralizedNewtypeDeriving
      - KindSignatures
      - MultiParamTypeClasses
    other-modules:
      - GaloisField
      - PrimeField
      - PolynomialRing
      - ExtensionField
      - Benchmarks
